# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(379, 596)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(240, 50, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(240, 80, 91, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(240, 110, 91, 21))
        self.label_6.setObjectName("label_6")
        self.x_min = QtWidgets.QTextEdit(Widget)
        self.x_min.setGeometry(QtCore.QRect(70, 80, 61, 21))
        self.x_min.setObjectName("x_min")
        self.x_max = QtWidgets.QTextEdit(Widget)
        self.x_max.setGeometry(QtCore.QRect(70, 110, 61, 21))
        self.x_max.setObjectName("x_max")
        self.y_min = QtWidgets.QTextEdit(Widget)
        self.y_min.setGeometry(QtCore.QRect(280, 80, 61, 21))
        self.y_min.setObjectName("y_min")
        self.y_max = QtWidgets.QTextEdit(Widget)
        self.y_max.setGeometry(QtCore.QRect(280, 110, 61, 21))
        self.y_max.setObjectName("y_max")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(240, 150, 101, 61))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Widget)
        self.comboBox.setGeometry(QtCore.QRect(80, 160, 91, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(Widget)
        self.label_7.setGeometry(QtCore.QRect(30, 160, 61, 41))
        self.label_7.setObjectName("label_7")
        self.imgshow = QtWidgets.QLabel(Widget)
        self.imgshow.setGeometry(QtCore.QRect(9, 255, 361, 321))
        self.imgshow.setText("")
        self.imgshow.setObjectName("imgshow")
        self.clear = QtWidgets.QCheckBox(Widget)
        self.clear.setGeometry(QtCore.QRect(250, 210, 86, 20))
        self.clear.setObjectName("clear")
        self.label_8 = QtWidgets.QLabel(Widget)
        self.label_8.setGeometry(QtCore.QRect(40, 200, 31, 41))
        self.label_8.setObjectName("label_8")
        self.expression = QtWidgets.QLineEdit(Widget)
        self.expression.setGeometry(QtCore.QRect(80, 210, 91, 21))
        self.expression.setObjectName("expression")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "自变量X范围："))
        self.label_2.setText(_translate("Widget", "因变量Y范围："))
        self.label_3.setText(_translate("Widget", "下限"))
        self.label_4.setText(_translate("Widget", "上限"))
        self.label_5.setText(_translate("Widget", "下限"))
        self.label_6.setText(_translate("Widget", "上限"))
        self.x_min.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-10</p></body></html>"))
        self.x_min.setPlaceholderText(_translate("Widget", "10"))
        self.x_max.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.y_min.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-10</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.y_max.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Widget", "开始计算"))
        self.comboBox.setItemText(0, _translate("Widget", "sin(x)"))
        self.comboBox.setItemText(1, _translate("Widget", "cos(x)"))
        self.comboBox.setItemText(2, _translate("Widget", "ln(x)"))
        self.comboBox.setItemText(3, _translate("Widget", "多项式"))
        self.comboBox.setItemText(4, _translate("Widget", "1/x"))
        self.label_7.setText(_translate("Widget", "函数体"))
        self.clear.setText(_translate("Widget", "清除记忆"))
        self.label_8.setText(_translate("Widget", "y  ="))
